---
# Python 3 support
pip_virtualenv_command: /usr/bin/python3 -m virtualenv # 
pip_package: python3-pip                               # geerlingguy.pip

# PostgreSQL
postgresql_objects_users:
  - name: galaxy
postgresql_objects_databases:
  - name: galaxy
    owner: galaxy

# PostgreSQL Backups
postgresql_backup_dir: /storage/backups
postgresql_backup_local_dir: "~postgres/backups"

# Galaxy
galaxy_create_user: true
galaxy_separate_privileges: true
galaxy_manage_paths: true
galaxy_root: /srv/galaxy
galaxy_layout: root-dir
#----------------------------------------------------------------------
galaxy_user: {name: galaxy, shell: /bin/bash, uid: 182649}
galaxy_group: {name: galaxy, gid: 70731}
#---------------------------------------------------------------------^
galaxy_commit_id: release_20.09
galaxy_force_checkout: true
miniconda_prefix: "{{ galaxy_tool_dependency_dir }}/_conda"
miniconda_version: 4.7.12
miniconda_manage_dependencies: false 

galaxy_config:
  galaxy:
#--Admin-------------------------------------------------        
    brand: "Oncotools"
    admin_users: flbernal@usit.uio.no,sigven@uio.no
    database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
    file_path: /storage
    new_file_path: /storage/tmp    
    check_migrate_tools: false
#--GDPR-----------------------------------------------------
    enable_beta_gdpr: true
    terms_url: https://dev.oncotools.elixir.no/galaxy-terms/
#--Jobs Configuration----------------------------------------
    job_config_file: "{{ galaxy_config_dir }}/job_conf.xml"  
#--Standard Setup---------------------------------------------------------------^
    # welcome_url: /static/welcome.html # This tells me where to find it
#--Oncotools Setup---------------------------------------------------------------^
    welcome_url: /static/welcome_onco.html # This tells me where to find it
#-- Tool Configuration----------------------------------------
    tool_data_path: "{{ galaxy_mutable_data_dir }}/tool-data"
    tool_config_file: "{{ galaxy_server_dir }}/config/tool_conf.xml"    
    tool_destinations_config_file: "{{ galaxy_config_dir }}/tool_destinations.yml"
    dependency_resolvers_config_file: "{{ galaxy_config_dir }}/dependency_resolvers_conf.xml"    

#-- UWSGI Configuration --------------------------------------------------------------------^    
  uwsgi:
    socket: 127.0.0.1:8080 # uncomment when SSL are in place
    # http: 0.0.0.0:8080
    buffer-size: 16384
    processes: 1
    threads: 4
    offload-threads: 2
    static-map:
      - /static={{ galaxy_server_dir }}/static
      - /favicon.ico={{ galaxy_server_dir }}/static/favicon.ico
    static-safe: client/galaxy/images
    master: true
    virtualenv: "{{ galaxy_venv_dir }}"
    pythonpath: "{{ galaxy_server_dir }}/lib"
    module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
    thunder-lock: true
    die-on-term: true
    hook-master-start:
      - unix_signal:2 gracefully_kill_them_all
      - unix_signal:15 gracefully_kill_them_all
    py-call-osafterfork: true
    enable-threads: true
    mule:
      - lib/galaxy/main.py
      - lib/galaxy/main.py
    farm: job-handlers:1,2

#-- Galaxy Config Files----------------------------------------
galaxy_config_files:
  - src: files/galaxy/config/job_conf.xml
    dest: "{{ galaxy_config.galaxy.job_config_file }}"    

#-- Oncotool tool---------------------------------------- 
galaxy_local_tools:
- oncoenrichr_wrapper.xml


# systemd
galaxy_systemd_mode: mule
galaxy_zergpool_listen_addr: 127.0.0.1:8080
galaxy_restart_handler_name: "Restart Galaxy"    
