---
- name: Deploying Docker
  block:

    # vars_files:
    #   - vars/cleaning
    #   - vars/repos
    #   - vars/dockerpkg
    
    - name: Update and upgrade all apt packages
      apt:
        update_cache: yes
        force_apt_get: yes
        upgrade: dist

    - name: Uninstall old versions
      apt:
        state: absent
        pkg: "{{ item.prepackage }}"
      loop: "{{ cleaning }}"
          
    - name: Set up the repository
      apt:
        state: present
        pkg: "{{ item.srepos }}"
      loop: "{{ repos }}"

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adding repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Re-update and re-upgrade and install Docker packages
      apt:
        update_cache: yes
        force_apt_get: yes
        state: present
        pkg: "{{ item.dpackage }}"
      loop: "{{ docker_packages }}"

    - name: Copy daemon.json file to /etc/docker/
      copy:
        src: ./roles/oncotools.docker/files/daemon.json
        dest: /etc/docker/
        


  
