---
- name: Volume Mounting and Docker
  block:
    - name: Create directory for local VM container storage
      ansible.builtin.file:
        path: /docker
        state: directory
        mode: '0755'

    - name: Create a new ext4 primary partition
      community.general.parted:
        device: /dev/sdb
        number: 1
        state: present

    - name: Create a ext4 filesystem on the volume at /dev/sdb1
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb1

    - name: Mount up device to Docker mountpoint
      ansible.posix.mount:
        path: /docker
        src: /dev/sdb1
        fstype: ext4
        state: present
...        
  
