---
- name: Installing snapd
  apt:
    name: snapd
    state: present
  register: snapd_install

- name: Update snap
  command: snap install core; snap refresh core
  changed_when: true
  failed_when: false
  when: snapd_install is changed

- name: Install Certbot
  snap:
    name: certbot
    classic: yes

- name: Symlink certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

# - name: Run certbot standalone
#   command: certbot certonly --nginx

# - name: Test Automatic Renewal
#   command: certbot renew -dry-run
  



  
